Collection rarity based on normalised information content
divergencetech/ethier pull request #51
Opened 2022-08-04 09:55 UTC by aschlosberg

All rationale is explained in the documentation of `rarity.go`.

2022-08-08 13:55 UTC, cxkoda reviewed
Looks good to me. I double-checked the computation of entropy and self-information.

Should we add some tests?

2022-08-08 13:55 UTC, cxkoda commented on erc721/erc721.go
> +	Value       interface{} `json:"value"`
I read somewhere that `any` is more common now. Is that true?

2022-08-08 13:55 UTC, cxkoda commented on erc721/erc721.go
> +	DisplayType string      `json:"display_type,omitempty"`
Since we're already following the OS-defined standard, should we use an enum for this?

2022-08-08 13:55 UTC, cxkoda commented on erc721/rarity.go
> +// booleans).
why is this called bucket?

2022-08-08 13:55 UTC, cxkoda commented on erc721/rarity.go
> +	attributes := make(map[TokenID]map[string]string)
should we make the types more verbose?
```suggestion
        type AttributeType string
        type AttributeValue string
	distributions := make(map[AttributeType]map[AttributeValue]float64)
	counts := make(map[AttributeType]float64)
	attributes := make(map[TokenID]map[AttributeType]AttributeValue)
```

2022-08-08 13:55 UTC, cxkoda commented on erc721/rarity.go
> +				// and JSON is stupid.
:+1:

2022-08-08 13:55 UTC, cxkoda commented on erc721/rarity.go
> +	// precision of individual probabilities.
This is not completely correct IMO.

Intuitively I agree that `~1/N` determines the uncertainty in our probabilities and therefore the score (although I'd have to follow the details to be sure). but rounding the value is in any case less accurate (although negligibly so) than keeping the insignificant digits. So keeping the plain value with all digits is surely not invalid.
The rounding is more just for human convenience.

2022-08-09 08:15 UTC, cxkoda requested changes
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/51)* status: all files reviewed, 1 unresolved discussion (waiting on @aschlosberg)

___
*[`erc721/erc721.go` line 36 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N8cHRLiAYS7DafpXGcd-r2-36:-N90cUsp5QWXSMJdLlVe:b-yqbdts) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/erc721.go#L36)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Making it an enum blocks any extended use cases for arbitrarily defined display types that someone may want to use.
</blockquote></details>

I agree with that. However, the whole structure of this package is very much tailored to the use with OS. So limiting this to OS supported values would reduce misuse.
___
*[`erc721/rarity.go` line 42 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N8cHRLiAYS7DafpXGce-r2-42:-N90d3U9EAG_CBovGgCT:bq657mq) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/rarity.go#L42)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Borrowed from histogram "buckets" or "bins".
</blockquote></details>

ah I see, as in "give me the bin that you would like me to count this for".
I found this a little confusing initially - but I get it now.
___
*[`erc721/rarity.go` line 50 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N8cHRLiAYS7DafpXGce-r2-50:-N90eG97951s1wu3u4qm:b-pbow6w) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/rarity.go#L50)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

There's a trade-off between type safety and usability. Forcing type assertions from string to `type Foo string` is a huge pain so I don't think it's worth it for an internal type.
</blockquote></details>

I found it hard to understand which map key was for what when I read the code first. But I'm happy to keep it as it is.
___
*[`erc721/rarity.go` line 106 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N8cHRLiAYS7DafpXGce-r2-106:-N90eluNCQ2hRWF-qYxP:bazdshf) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/rarity.go#L106)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

I want to avoid people reading any meaning into the insignificant digits. Of course there's a [Wikipedia entry](https://en.wikipedia.org/wiki/Significant_figures#Arithmetic) about this. Sharing so we can discuss offline but have it recorded here.
</blockquote></details>

Had another think about this over night, but let's move it offline.


<!-- Sent from Reviewable.io -->

2022-08-09 08:47 UTC, cxkoda requested changes
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/51)* status: all files reviewed, 2 unresolved discussions (waiting on @aschlosberg)

___
*[`erc721/rarity.go` line 113 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N90kKEoALICHd7e5b6m:-N90kKEoALICHd7e5b6n:bafrcz2) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/rarity.go#L113)):*
> ```Go
> 			return math.Round(f*pow) / pow
> 		}
> 	})()
> ```

Here a quick example. Assume we have a collection of 6 tokens with 1 trait. The trait has 3 different values A,B,C that occur 1,2,3 times.
The relative self-information score for tokens with A,B,C is `{1.77156, 1.08622, 0.685331}`. Rounding this with the above logic results in the values `{2., 1., 1.}`. So it would suggest that having B and C is as rare, which is not the case. 



_Code quote:_
```Go
	scale := (func() func(float64) float64 {
		precision := int(math.Floor(math.Log10(float64(len(coll)))))
		pow := math.Pow10(precision)
		return func(f float64) float64 {
			return math.Round(f*pow) / pow
		}
	})()
```


<!-- Sent from Reviewable.io -->

2022-08-12 10:34 UTC, aschlosberg reviewed
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/51)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @cxkoda)

___
*[`erc721/erc721.go` line 36 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N8cHRLiAYS7DafpXGcd-r2-36:-N9GbKKR4hc0CV6hFiCj:b-8n6uvh) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/erc721.go#L36)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

I agree with that. However, the whole structure of this package is very much tailored to the use with OS. So limiting this to OS supported values would reduce misuse.
</blockquote></details>

Done. This was such a pain!
___
*[`erc721/rarity.go` line 50 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N8cHRLiAYS7DafpXGce-r2-50:-N9GWIlGBvhfUmks1btK:b-lhuoxu) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/rarity.go#L50)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

I found it hard to understand which map key was for what when I read the code first. But I'm happy to keep it as it is.
</blockquote></details>

I've added type aliases to make this easier. They don't add type safety, but they make it more readable.
___
*[`erc721/rarity.go` line 106 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N8cHRLiAYS7DafpXGce-r2-106:-N9GWPeeECt7nbtdIz74:bg91ird) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/rarity.go#L106)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

Had another think about this over night, but let's move it offline.
</blockquote></details>

I've removed it after our discussion about the collection being the population not a sample and therefore without measurement error.
___
*[`erc721/rarity.go` line 113 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N90kKEoALICHd7e5b6m:-N9GWXER-wCCYrhpcVXV:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/rarity.go#L113)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

Here a quick example. Assume we have a collection of 6 tokens with 1 trait. The trait has 3 different values A,B,C that occur 1,2,3 times.
The relative self-information score for tokens with A,B,C is `{1.77156, 1.08622, 0.685331}`. Rounding this with the above logic results in the values `{2., 1., 1.}`. So it would suggest that having B and C is as rare, which is not the case. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-12 10:59 UTC, cxkoda approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aschlosberg)

___
*[`erc721/erc721.go` line 36 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N8cHRLiAYS7DafpXGcd-r2-36:-N9Gga47-zArjYAZ6AXY:bnxosu2) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/erc721.go#L36)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Done. This was such a pain!
</blockquote></details>

Argh, sorry for that. Thanks!
___
*[`erc721/rarity.go` line 50 at r2](https://reviewable.io/reviews/divergencetech/ethier/51#-N8cHRLiAYS7DafpXGce-r2-50:-N9GgxXpD1stI7_b24fZ:b4pkhwa) ([raw file](https://github.com/divergencetech/ethier/blob/490ba82e6d164a168231979c5fe27f4e72655e55/erc721/rarity.go#L50)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

I've added type aliases to make this easier. They don't add type safety, but they make it more readable.
</blockquote></details>

Ohh I wasn't aware that there are type aliases in go. Thanks, this is great!


<!-- Sent from Reviewable.io -->

2022-08-12 11:13 UTC, merged